package constant

const PORT = "PORT"

const (
	DB_HOST     = "DB_HOST"
	DB_PORT     = "DB_PORT"
	DB_USERNAME = "DB_USERNAME"
	DB_PASSWORD = "DB_PASSWORD"
	DB_NAME     = "DB_NAME"
)

const (
	JWT_SECRET_KEY      = "JWT_SECRET_KEY"
	JWT_EXPIRE_DURATION = "JWT_EXPIRE_DURATION"
)

const (
	AI_API_KEY = "AI_API_KEY"
	AI_MODEL   = "AI_MODEL"
)

const (
	ADMIN_USERNAME = "ADMIN_USERNAME"
	ADMIN_EMAIL    = "ADMIN_EMAIL"
	ADMIN_PASSWORD = "ADMIN_PASSWORD"
)

const (
	CLOUDINARY_CLOUD_NAME  = "CLOUDINARY_CLOUD_NAME"
	CLOUDINARY_API_KEY     = "CLOUDINARY_API_KEY"
	CLOUDINARY_API_SECRET  = "CLOUDINARY_API_SECRET"
)
